name: 'Automerge Dependabot'
on:
  pull_request:

jobs:
  merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Automerge Pull Request
        uses: EstebanBorai/automerge-dependabot-action@0.1.0
